### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/sys/fs/cgroup/blkio/blkio.throttle.io_service_bytes'

### ISSUE THREAD

**Issue by hasufell** [yadutaf/ctop#15] opened 2016-01-11 23:48 UTC
docker is running, yet ctop fails to start

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/ctop", line 4, in <module>
    cgroup_top.main()
  File "/usr/lib64/python2.7/site-packages/cgroup_top.py", line 887, in main
    collect(measures)
  File "/usr/lib64/python2.7/site-packages/cgroup_top.py", line 349, in collect
    cur[cgroup.name]['blkio.throttle.io_service_bytes'] = cgroup['blkio.throttle.io_service_bytes']
  File "/usr/lib64/python2.7/site-packages/cgroup_top.py", line 245, in __getitem__
    with open(path) as f:
IOError: [Errno 2] No such file or directory: '/sys/fs/cgroup/blkio/blkio.throttle.io_service_bytes'
```

**Comment by yadutaf** [comment] 2016-01-13 08:19
Hi,

I'll try to reproduce it this week-end. Which distribution, kernel and docker version are you running ?

**Comment by hasufell** [comment] 2016-01-13 12:42
- gentoo
- kernel 3.18.24
- Docker version 1.9.1, build a34a1d5

**Comment by yadutaf** [comment] 2016-01-18 22:21
Hum... That's weird. Maybe some kernel version. Can you run a `ls /sys/fs/cgroup/blkio/` as well as one of the sub-folders ? Ctop first checks thats the controller exists, then lists containers in the controller before attempting to read it.

In last resort, I'll just add a "if" to fix the effect but I'd rather understand what's going on.

**Comment by hasufell** [comment] 2016-01-18 22:37
```
# ls /sys/fs/cgroup/blkio/
blkio.reset_stats      cgroup.procs          docker             release_agent
cgroup.clone_children  cgroup.sane_behavior  notify_on_release  tasks
# ls /sys/fs/cgroup/blkio/docker/
blkio.reset_stats  cgroup.clone_children  cgroup.procs  notify_on_release  tasks
```

**Comment by yadutaf** [comment] 2016-01-19 07:38
Looks like a broken blkio controller on your system. I've pushed a blkio specific workaround on https://github.com/yadutaf/ctop/tree/jt-broken-blkio. Can you test and confirm it works or report any other broken controller ?

**Comment by hasufell** [comment] 2016-01-19 12:30
> Looks like a broken blkio controller on your system.

What do you mean by broken? What is supposed to create that file? Ctop doesn't document the required kernel features.

> I've pushed a blkio specific workaround on

That works, but I think this might be a documentation issue.

**Comment by yadutaf** [comment] 2016-01-19 13:49
Thanks for your test, I'll merge the branch.

The "files" are managed by the kernel, in the cgroup controllers, like the pseudo-files in /proc. ctop in itself does not require any of these files BUT it assumes that, if the controller is active and marked as available on the system, it should show some well documented pseudo-files. For some reason, this system appears to report the blkio controller as available and enabled but fails to report any blkio status files.

**Comment by hasufell** [comment] 2016-01-19 13:52
> For some reason, this system appears to report the blkio controller as available and enabled but fails to report any blkio status files.

Is it documented anywhere that the files can be assumed to exist?

**Closed as completed** 2016-01-19 18:46 UTC

**Comment by yadutaf** [comment] 2016-01-19 18:47
Merged. Thanks for the feedback.
