### ISSUE TITLE
KeyError: 'tasks' when running

### ISSUE THREAD

**Issue by johanbrandhorst** [yadutaf/ctop#45] opened 2017-06-03 20:37 UTC
Hi, I love `ctop`, and it usually works well for me, but today I installed `ctop` from `apt`, and when I ran it, I got the following stacktrace and error:

```bash
root@hostname:~# ctop
Traceback (most recent call last):
  File "/usr/bin/ctop", line 4, in <module>
    cgroup_top.main()
  File "/usr/lib/python3/dist-packages/cgroup_top.py", line 795, in main
    results = built_statistics(measures, CONFIGURATION)
  File "/usr/lib/python3/dist-packages/cgroup_top.py", line 359, in built_statistics
    'tasks': len(data['tasks']),
KeyError: 'tasks'
```

Not sure if the `ctop` version is old and this is an irrelevant bug, nonetheless there it is. I'm using `ctop/xenial,now 0.4.1-1 all [installed]`.

**Comment by yadutaf** [comment] 2017-06-05 14:34
Thanks for for taking the time to report this issue ! I've tried to reproduce this bug on a xenial with a fresh install from apt and could not reproduce this issue. Is it something you see frequently or is there any specific scenario to reproduce it ?

In particular, do you use systemd (the default on Ubuntu) ? Which container system do you use if any (lxc, docker, custom, ...) ?

**Comment by johanbrandhorst** [comment] 2017-06-05 14:36
I installed `ctop` on a fresh deploy of the "Docker" "Imagehub" on Scaleway and it happened with or without any containers running. I can reproduce it every time. Want me to run some debugging commands?

**Comment by yadutaf** [comment] 2017-06-05 14:52
I've pinged Scaleway on Twitter. Hopefully they have some spare credits to debug. Feel free to ping me again later this week If I forget to come with any news. In the mean time, If you could try again with the version from Git, to confirm the bug still exists, that would be great !

**Comment by johanbrandhorst** [comment] 2017-06-05 14:58
Confirmed not occurring on master. It's a problem with the `xenial` version it appears.

**Comment by yadutaf** [comment] 2017-07-27 20:07
Closing as confirmed fixed. Thanks for the test.

**Closed as completed by yadutaf** 2017-07-27 20:07 UTC
